name: A workflow for my Hello World file
on: push
jobs:
  build:
    name: Hello World action
    runs-on: ubunto-latest
    steps:
      - uses: actions/checkout@1
      - uses: ./action-a
        with:
          MY_NAME: "Mona"
